format="""
$python\
[](bg:#434C5E fg:#434C5E)\
[ ](bg:#434C5E fg:#ffffff)\
$directory\
[](fg:#434C5E bg:#842FB4)\
$git_branch\
$git_status\
[](fg:#842FB4 bg:#B02FCD)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#B02FCD bg:#CB68EE)\
$docker_context\
[](fg:#CB68EE bg:#FF9AF1)\
$time\
[ ](fg:#FF9AF1)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space

[directory]
style = "bg:#434C5E fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#b02fdc fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#842fb4"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#842fb4"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#B02FCD"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#B02FCD"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#FF9AF1 fg:#000000"
format = '[ $time ]($style)'

[custom.os]
command = "uname -s"
when = "true"
format = "OS: [$output]($style) "
style = "bold green"


